import { Gift, MapPin, Users, Clock, Calendar, Camera, Palette, Music, Coffee, BookOpen, Star, Award, Utensils, Wave, Anchor, Mountain, Wind, HeartPulse, Dumbbell, Sunrise, PlaneTakeoff, Tent, TreePine, Droplets, Leaf, Gamepad2, MicVocal, Sparkles, Snowflake, TestTube, Rabbit } from "lucide-react";

export interface Experience {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  price: number;
  location: string;
  duration: string;
  participants: string;
  date: string;
  category: string;
  trending?: boolean;
  featured?: boolean;
  nicheCategory?: string;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
  icon: any;
}

// Cart related types
export interface CartItem {
  experienceId: string;
  quantity: number;
}

export const nicheCategories = [
  "Photography",
  "Art & Crafts",
  "Music",
  "Cooking",
  "Literature",
  "Astronomy",
  "Heritage",
  "Sustainable",
  "Water Sports",
  "Mountain",
  "Wildlife",
  "Meditation",
  "Fitness",
  "Spiritual",
  "Aviation",
  "Camping",
  "Nature",
  "Spa & Wellness",
  "Gaming",
  "Performance Arts",
  "Seasonal",
  "Science",
  "Pet-friendly",
  "Extreme Sports"
];

export const experiences: Experience[] = [
  // ... keep existing code (first 18 experiences)
  
  {
    id: "exp19",
    title: "Photography Expedition: Western Ghats",
    description: "Capture the biodiversity hotspot of Western Ghats with expert wildlife photographers guiding you to perfect shots.",
    imageUrl: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?q=80&w=2425&auto=format&fit=crop",
    price: 28900,
    location: "Western Ghats, Karnataka",
    duration: "3 days",
    participants: "Small group (4-6)",
    date: "October-May",
    category: "learning",
    nicheCategory: "Photography"
  },
  {
    id: "exp20",
    title: "Pottery Workshop in Andretta",
    description: "Learn traditional pottery techniques in the artist village of Andretta from master craftsmen in a scenic studio.",
    imageUrl: "https://images.unsplash.com/photo-1565122256258-9a86310fecd4?q=80&w=2670&auto=format&fit=crop",
    price: 15900,
    location: "Andretta, Himachal Pradesh",
    duration: "2 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Art & Crafts"
  },
  {
    id: "exp21",
    title: "Carnatic Music Immersion",
    description: "Immerse yourself in the classical music tradition of South India with private lessons from renowned musicians.",
    imageUrl: "https://images.unsplash.com/photo-1627734819947-e107fe9a8ce3?q=80&w=2670&auto=format&fit=crop",
    price: 22500,
    location: "Chennai, Tamil Nadu",
    duration: "5 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Music"
  },
  {
    id: "exp22",
    title: "Goa Spice Plantation Culinary Tour",
    description: "Explore organic spice plantations and learn to cook authentic Goan cuisine with freshly harvested ingredients.",
    imageUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?q=80&w=2187&auto=format&fit=crop",
    price: 12900,
    location: "Ponda, Goa",
    duration: "1 day",
    participants: "2 people",
    date: "Year-round",
    category: "dining",
    nicheCategory: "Cooking"
  },
  {
    id: "exp23",
    title: "Literary Walking Tour of Kolkata",
    description: "Follow in the footsteps of Tagore, Ray, and other Bengali literary giants through the cultural heart of Kolkata.",
    imageUrl: "https://images.unsplash.com/photo-1600600423621-70c9f4416106?q=80&w=2585&auto=format&fit=crop",
    price: 8900,
    location: "Kolkata, West Bengal",
    duration: "4 hours",
    participants: "1-4 people",
    date: "October-March",
    category: "learning",
    nicheCategory: "Literature"
  },
  {
    id: "exp24",
    title: "Ladakh Astronomy Retreat",
    description: "Stargaze from one of the darkest skies on earth with professional-grade telescopes and expert astronomers.",
    imageUrl: "https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?q=80&w=2670&auto=format&fit=crop",
    price: 39900,
    location: "Ladakh",
    duration: "4 days",
    participants: "2 people",
    date: "June-September",
    category: "adventure",
    nicheCategory: "Astronomy"
  },
  {
    id: "exp25",
    title: "Chettinad Heritage Mansion Stay",
    description: "Experience life in a meticulously restored 100-year-old mansion with traditional Chettinad hospitality and cuisine.",
    imageUrl: "https://images.unsplash.com/photo-1582972236019-ea4af5ffe587?q=80&w=2670&auto=format&fit=crop",
    price: 27500,
    location: "Karaikudi, Tamil Nadu",
    duration: "2 days",
    participants: "2 people",
    date: "Year-round",
    category: "luxury",
    nicheCategory: "Heritage"
  },
  {
    id: "exp26",
    title: "Sustainable Farm Immersion",
    description: "Live and work on an award-winning sustainable farm, learning permaculture principles and eco-friendly living.",
    imageUrl: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?q=80&w=2670&auto=format&fit=crop",
    price: 19900,
    location: "Auroville, Tamil Nadu",
    duration: "5 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Sustainable"
  },
  {
    id: "exp27",
    title: "Surfing Lessons in Varkala",
    description: "Learn to ride the waves with professional instructors on the picturesque beaches of Varkala.",
    imageUrl: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?q=80&w=2670&auto=format&fit=crop",
    price: 14500,
    location: "Varkala, Kerala",
    duration: "3 days",
    participants: "1 person",
    date: "October-May",
    category: "adventure",
    nicheCategory: "Water Sports"
  },
  {
    id: "exp28",
    title: "Mountain Biking in Manali",
    description: "Adventure through Himalayan trails on a high-performance mountain bike with experienced guides.",
    imageUrl: "https://images.unsplash.com/photo-1539782761833-03502a7a3e48?q=80&w=2574&auto=format&fit=crop",
    price: 24900,
    location: "Manali, Himachal Pradesh",
    duration: "2 days",
    participants: "1 person",
    date: "April-October",
    category: "adventure",
    nicheCategory: "Mountain"
  },
  {
    id: "exp29",
    title: "Tiger Safari at Bandhavgarh",
    description: "Track wild tigers in their natural habitat with expert naturalists in one of India's premier tiger reserves.",
    imageUrl: "https://images.unsplash.com/photo-1549366021-9f761d450615?q=80&w=2670&auto=format&fit=crop",
    price: 35900,
    location: "Bandhavgarh, Madhya Pradesh",
    duration: "3 days",
    participants: "2 people",
    date: "October-June",
    category: "adventure",
    nicheCategory: "Wildlife"
  },
  {
    id: "exp30",
    title: "Vipassana Meditation Retreat",
    description: "Experience the ancient meditation technique of Vipassana in a serene environment with qualified teachers.",
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=2622&auto=format&fit=crop",
    price: 15000,
    location: "Igatpuri, Maharashtra",
    duration: "10 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Meditation"
  },
  {
    id: "exp31",
    title: "Himalayan Fitness Bootcamp",
    description: "Transform your fitness with high-altitude training, yoga, and nutrition counseling in a mountain setting.",
    imageUrl: "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?q=80&w=2531&auto=format&fit=crop",
    price: 32900,
    location: "Dharamshala, Himachal Pradesh",
    duration: "7 days",
    participants: "1 person",
    date: "April-October",
    category: "wellness",
    nicheCategory: "Fitness"
  },
  {
    id: "exp32",
    title: "Spiritual Journey to Varanasi",
    description: "Experience the spiritual heart of India with a guided exploration of ancient rituals, temples, and philosophy.",
    imageUrl: "https://images.unsplash.com/photo-1561361058-c24cecda37fc?q=80&w=2670&auto=format&fit=crop",
    price: 22500,
    location: "Varanasi, Uttar Pradesh",
    duration: "4 days",
    participants: "2 people",
    date: "October-March",
    category: "wellness",
    nicheCategory: "Spiritual"
  },
  {
    id: "exp33",
    title: "Paragliding Over Bir Billing",
    description: "Soar over the Himalayas with a tandem paragliding experience from one of the world's best paragliding sites.",
    imageUrl: "https://images.unsplash.com/photo-1622442566860-24eb7e38be80?q=80&w=2574&auto=format&fit=crop",
    price: 18900,
    location: "Bir, Himachal Pradesh",
    duration: "1 day",
    participants: "1 person",
    date: "March-June, September-November",
    category: "adventure",
    nicheCategory: "Aviation"
  },
  {
    id: "exp34",
    title: "Lakeside Camping in Pangong",
    description: "Camp under the stars beside the ethereal blue waters of Pangong Lake with luxury tents and local cuisine.",
    imageUrl: "https://images.unsplash.com/photo-1496080174650-637e3f22fa03?q=80&w=2619&auto=format&fit=crop",
    price: 29900,
    location: "Pangong Lake, Ladakh",
    duration: "2 days",
    participants: "2 people",
    date: "May-September",
    category: "adventure",
    nicheCategory: "Camping"
  },
  {
    id: "exp35",
    title: "Valley of Flowers Trek",
    description: "Trek through UNESCO World Heritage site known for its meadows of endemic alpine flowers and stunning landscapes.",
    imageUrl: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?q=80&w=2674&auto=format&fit=crop",
    price: 24900,
    location: "Uttarakhand",
    duration: "6 days",
    participants: "1 person",
    date: "July-September",
    category: "adventure",
    nicheCategory: "Nature"
  },
  {
    id: "exp36",
    title: "Ayurvedic Panchakarma Retreat",
    description: "Experience a complete detoxification and rejuvenation program based on ancient Ayurvedic principles.",
    imageUrl: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?q=80&w=2670&auto=format&fit=crop",
    price: 48900,
    location: "Kovalam, Kerala",
    duration: "14 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spa & Wellness"
  },
  {
    id: "exp37",
    title: "E-Sports Gaming Tournament",
    description: "Participate in a professional e-sports tournament with high-end gaming setups and competitive gameplay.",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2670&auto=format&fit=crop",
    price: 15900,
    location: "Bengaluru, Karnataka",
    duration: "2 days",
    participants: "1 person",
    date: "Scheduled events",
    category: "learning",
    nicheCategory: "Gaming"
  },
  {
    id: "exp38",
    title: "Classical Dance Workshop",
    description: "Learn the fundamentals of Bharatanatyam, Kathak, or Odissi from master performers in an immersive setting.",
    imageUrl: "https://images.unsplash.com/photo-1516307343428-2f99b49942a2?q=80&w=2670&auto=format&fit=crop",
    price: 18500,
    location: "Multiple locations",
    duration: "5 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Performance Arts"
  },
  {
    id: "exp39",
    title: "Himalayan Snow Adventure",
    description: "Experience snowboarding, skiing, and snowshoeing in pristine Himalayan winter landscapes.",
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?q=80&w=2670&auto=format&fit=crop",
    price: 32900,
    location: "Gulmarg, Kashmir",
    duration: "4 days",
    participants: "1 person",
    date: "December-March",
    category: "adventure",
    nicheCategory: "Seasonal"
  },
  {
    id: "exp40",
    title: "Rocket Launch Viewing Experience",
    description: "Witness a live ISRO rocket launch with expert commentary and behind-the-scenes insights.",
    imageUrl: "https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?q=80&w=2670&auto=format&fit=crop",
    price: 29900,
    location: "Sriharikota, Andhra Pradesh",
    duration: "2 days",
    participants: "1 person",
    date: "Based on launch schedule",
    category: "learning",
    nicheCategory: "Science"
  },
  {
    id: "exp41",
    title: "Pet-Friendly Beach Retreat",
    description: "Enjoy a luxurious beachfront stay with specially designed activities and amenities for you and your pet.",
    imageUrl: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?q=80&w=2588&auto=format&fit=crop",
    price: 26900,
    location: "Goa",
    duration: "3 days",
    participants: "2 people + 1 pet",
    date: "October-March",
    category: "luxury",
    nicheCategory: "Pet-friendly"
  },
  {
    id: "exp42",
    title: "Rock Climbing in Hampi",
    description: "Scale the unique boulder formations of Hampi with professional climbing instructors and top-grade equipment.",
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?q=80&w=2803&auto=format&fit=crop",
    price: 19900,
    location: "Hampi, Karnataka",
    duration: "3 days",
    participants: "1 person",
    date: "October-March",
    category: "adventure",
    nicheCategory: "Extreme Sports"
  },
  {
    id: "exp43",
    title: "Underwater Photography Workshop",
    description: "Master the art of underwater photography in the crystal-clear waters of Andaman with marine life experts.",
    imageUrl: "https://images.unsplash.com/photo-1682686580950-960d1d513532?q=80&w=2670&auto=format&fit=crop",
    price: 45900,
    location: "Havelock Island, Andaman",
    duration: "5 days",
    participants: "1 person",
    date: "November-May",
    category: "learning",
    nicheCategory: "Photography"
  },
  {
    id: "exp44",
    title: "Marble Inlay Art Workshop",
    description: "Learn the intricate art of pietra dura marble inlay from master craftsmen near the Taj Mahal.",
    imageUrl: "https://images.unsplash.com/photo-1642029480082-cf375eede744?q=80&w=2574&auto=format&fit=crop",
    price: 18900,
    location: "Agra, Uttar Pradesh",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Art & Crafts"
  },
  {
    id: "exp45",
    title: "Classical Instrument Masterclass",
    description: "Learn to play the sitar, tabla, or sarod with personalized instruction from nationally recognized musicians.",
    imageUrl: "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?q=80&w=2670&auto=format&fit=crop",
    price: 24500,
    location: "Multiple locations",
    duration: "10 sessions",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Music"
  },
  {
    id: "exp46",
    title: "Himalayan Truffle Hunting",
    description: "Search for rare Himalayan truffles with expert foragers and learn to prepare gourmet dishes with your finds.",
    imageUrl: "https://images.unsplash.com/photo-1585668542138-08c44ebb61dc?q=80&w=2574&auto=format&fit=crop",
    price: 32900,
    location: "Himachal Pradesh",
    duration: "2 days",
    participants: "2 people",
    date: "Seasonal (May-June)",
    category: "dining",
    nicheCategory: "Cooking"
  },
  {
    id: "exp47",
    title: "Rare Book Collection Tour",
    description: "Explore private collections of rare manuscripts and first editions with literary historians and archivists.",
    imageUrl: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=2453&auto=format&fit=crop",
    price: 12900,
    location: "Delhi, Mumbai, Kolkata",
    duration: "1 day",
    participants: "1-2 people",
    date: "By appointment",
    category: "learning",
    nicheCategory: "Literature"
  },
  {
    id: "exp48",
    title: "Meteor Shower Camping",
    description: "Camp in the remote desert during peak meteor shower seasons with astronomy guides and night sky photography.",
    imageUrl: "https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?q=80&w=2670&auto=format&fit=crop",
    price: 25900,
    location: "Spiti Valley, Himachal Pradesh",
    duration: "2 nights",
    participants: "2 people",
    date: "During meteor showers",
    category: "adventure",
    nicheCategory: "Astronomy"
  },
  {
    id: "exp49",
    title: "Palace to Palace Heritage Tour",
    description: "Travel through time with exclusive access to private royal residences not open to the general public.",
    imageUrl: "https://images.unsplash.com/photo-1610541149288-c78bedf8a0b2?q=80&w=2670&auto=format&fit=crop",
    price: 89900,
    location: "Rajasthan",
    duration: "7 days",
    participants: "2 people",
    date: "October-March",
    category: "luxury",
    nicheCategory: "Heritage"
  },
  {
    id: "exp50",
    title: "Zero-Waste Lifestyle Retreat",
    description: "Transform your daily habits with practical workshops on sustainable living, composting, and upcycling.",
    imageUrl: "https://images.unsplash.com/photo-1528190336454-13cd56b45b5a?q=80&w=2670&auto=format&fit=crop",
    price: 21900,
    location: "Kodaikanal, Tamil Nadu",
    duration: "5 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Sustainable"
  },
  {
    id: "exp51",
    title: "Private Island Kayaking Expedition",
    description: "Paddle through the secluded backwaters and islands of Lakshadweep with expert guides and camping equipment.",
    imageUrl: "https://images.unsplash.com/photo-1577871349005-073d07e5f4db?q=80&w=2586&auto=format&fit=crop",
    price: 37900,
    location: "Lakshadweep Islands",
    duration: "5 days",
    participants: "2 people",
    date: "November-April",
    category: "adventure",
    nicheCategory: "Water Sports"
  },
  {
    id: "exp52",
    title: "Himalayan Peak Climbing Expedition",
    description: "Summit a 6000m Himalayan peak with professional mountaineers in a fully supported expedition.",
    imageUrl: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?q=80&w=2670&auto=format&fit=crop",
    price: 129900,
    location: "Uttarakhand",
    duration: "18 days",
    participants: "1 person",
    date: "May-June, September-October",
    category: "adventure",
    nicheCategory: "Mountain"
  },
  {
    id: "exp53",
    title: "Bird Photography in Bharatpur",
    description: "Capture rare migratory birds with specialized photography equipment and expert ornithologists.",
    imageUrl: "https://images.unsplash.com/photo-1520808663317-647b476a81b9?q=80&w=2573&auto=format&fit=crop",
    price: 24900,
    location: "Bharatpur, Rajasthan",
    duration: "3 days",
    participants: "1 person",
    date: "October-March",
    category: "learning",
    nicheCategory: "Wildlife"
  },
  {
    id: "exp54",
    title: "Silent Meditation in Ancient Cave",
    description: "Experience profound meditation in ancient caves once used by Buddhist monks, with expert guidance.",
    imageUrl: "https://images.unsplash.com/photo-1519834825367-a1e1feaebcce?q=80&w=2574&auto=format&fit=crop",
    price: 19900,
    location: "Ajanta, Maharashtra",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Meditation"
  },
  {
    id: "exp55",
    title: "Himalayan Marathon Training",
    description: "Train for high-altitude marathon with personalized coaching, nutrition planning, and acclimatization.",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=2670&auto=format&fit=crop",
    price: 45900,
    location: "Leh, Ladakh",
    duration: "14 days",
    participants: "1 person",
    date: "April-September",
    category: "wellness",
    nicheCategory: "Fitness"
  },
  {
    id: "exp56",
    title: "Monastery Retreat with Buddhist Monks",
    description: "Live alongside Buddhist monks learning meditation techniques, philosophy, and participating in daily rituals.",
    imageUrl: "https://images.unsplash.com/photo-1544015759-358a2e06db3d?q=80&w=2561&auto=format&fit=crop",
    price: 32900,
    location: "Sikkim",
    duration: "7 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spiritual"
  },
  {
    id: "exp57",
    title: "Helicopter Piloting Experience",
    description: "Take control of a helicopter with a certified flight instructor in a hands-on flying lesson with stunning views.",
    imageUrl: "https://images.unsplash.com/photo-1678622038591-12a8ba0e6b52?q=80&w=2670&auto=format&fit=crop",
    price: 59900,
    location: "Mumbai, Maharashtra",
    duration: "Half-day",
    participants: "1 person",
    date: "Year-round",
    category: "adventure",
    nicheCategory: "Aviation"
  },
  {
    id: "exp58",
    title: "Luxury Desert Camping",
    description: "Experience the Thar Desert in a luxury camp with private butler, gourmet dining, and cultural performances.",
    imageUrl: "https://images.unsplash.com/photo-1543424308-55c088616e45?q=80&w=2670&auto=format&fit=crop",
    price: 38900,
    location: "Jaisalmer, Rajasthan",
    duration: "2 days",
    participants: "2 people",
    date: "October-March",
    category: "luxury",
    nicheCategory: "Camping"
  },
  {
    id: "exp59",
    title: "Private Wildlife Reserve Experience",
    description: "Exclusive access to a private conservation area with personalized safari drives and conservation activities.",
    imageUrl: "https://images.unsplash.com/photo-1620961335082-2de5b7eb90be?q=80&w=2670&auto=format&fit=crop",
    price: 129900,
    location: "Madhya Pradesh",
    duration: "3 days",
    participants: "2 people",
    date: "October-June",
    category: "luxury",
    nicheCategory: "Nature"
  },
  {
    id: "exp60",
    title: "Luxury Floating Spa Experience",
    description: "Indulge in spa treatments on a private floating pavilion surrounded by serene backwaters.",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=2670&auto=format&fit=crop",
    price: 18900,
    location: "Kumarakom, Kerala",
    duration: "1 day",
    participants: "1-2 people",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spa & Wellness"
  },
  {
    id: "exp61",
    title: "VR Game Development Workshop",
    description: "Create your own virtual reality game with industry professionals using cutting-edge development tools.",
    imageUrl: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=2678&auto=format&fit=crop",
    price: 29900,
    location: "Hyderabad, Telangana",
    duration: "5 days",
    participants: "1 person",
    date: "Scheduled workshops",
    category: "learning",
    nicheCategory: "Gaming"
  },
  {
    id: "exp62",
    title: "Bollywood Dance Masterclass",
    description: "Learn signature Bollywood dance routines from professional choreographers who work in the film industry.",
    imageUrl: "https://images.unsplash.com/photo-1503162877534-8e76237adda2?q=80&w=2574&auto=format&fit=crop",
    price: 12900,
    location: "Mumbai, Maharashtra",
    duration: "2 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Performance Arts"
  },
  {
    id: "exp63",
    title: "Holi Festival Luxury Experience",
    description: "Celebrate Holi in a royal palace with organic colors, traditional music, and gourmet festival cuisine.",
    imageUrl: "https://images.unsplash.com/photo-1576074622916-192aa3264fb7?q=80&w=2680&auto=format&fit=crop",
    price: 34900,
    location: "Udaipur, Rajasthan",
    duration: "2 days",
    participants: "2 people",
    date: "During Holi festival",
    category: "luxury",
    nicheCategory: "Seasonal"
  },
  {
    id: "exp64",
    title: "Space Research Center Tour",
    description: "Behind-the-scenes tour of ISRO facilities with interactive demonstrations and meetings with scientists.",
    imageUrl: "https://images.unsplash.com/photo-1446776858070-70c3d5ed6758?q=80&w=2672&auto=format&fit=crop",
    price: 18900,
    location: "Bangalore, Karnataka",
    duration: "1 day",
    participants: "1 person",
    date: "Limited availability",
    category: "learning",
    nicheCategory: "Science"
  },
  {
    id: "exp65",
    title: "Luxury Pet Spa Retreat",
    description: "Pamper your pet with specialized treatments while you enjoy luxury accommodations and activities together.",
    imageUrl: "https://images.unsplash.com/photo-1518893494013-481c1d8ed3fd?q=80&w=2670&auto=format&fit=crop",
    price: 21900,
    location: "Lonavala, Maharashtra",
    duration: "2 days",
    participants: "1 person + 1 pet",
    date: "Year-round",
    category: "luxury",
    nicheCategory: "Pet-friendly"
  },
  {
    id: "exp66",
    title: "White Water Rafting Championship",
    description: "Join professional rafters for advanced training and participate in competitive rapids navigation.",
    imageUrl: "https://images.unsplash.com/photo-1534109287195-21fcc35b9beb?q=80&w=2670&auto=format&fit=crop",
    price: 26900,
    location: "Rishikesh, Uttarakhand",
    duration: "4 days",
    participants: "1 person",
    date: "Seasonal (May-June, September-October)",
    category: "adventure",
    nicheCategory: "Extreme Sports"
  },
  {
    id: "exp67",
    title: "Street Photography Workshop",
    description: "Capture the vibrant street life of India's most photogenic cities with award-winning photographers.",
    imageUrl: "https://images.unsplash.com/photo-1604537466608-109fa2f16c3b?q=80&w=2628&auto=format&fit=crop",
    price: 15900,
    location: "Varanasi, Uttar Pradesh",
    duration: "3 days",
    participants: "1 person",
    date: "October-March",
    category: "learning",
    nicheCategory: "Photography"
  },
  {
    id: "exp68",
    title: "Miniature Painting Workshop",
    description: "Learn the ancient art of Indian miniature painting with natural pigments and traditional techniques.",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=2690&auto=format&fit=crop",
    price: 16900,
    location: "Jaipur, Rajasthan",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Art & Crafts"
  },
  {
    id: "exp69",
    title: "Classical Music Festival VIP Pass",
    description: "Premium access to one of India's most prestigious classical music festivals with backstage artist meetings.",
    imageUrl: "https://images.unsplash.com/photo-1512053459797-38c3a066cabd?q=80&w=2670&auto=format&fit=crop",
    price: 28900,
    location: "Multiple locations",
    duration: "3-5 days",
    participants: "1 person",
    date: "Festival dates",
    category: "luxury",
    nicheCategory: "Music"
  },
  {
    id: "exp70",
    title: "Royal Kitchen Cooking Class",
    description: "Learn closely guarded family recipes from royal chefs in a historic palace kitchen.",
    imageUrl: "https://images.unsplash.com/photo-1556911261-6bd341186b2f?q=80&w=2670&auto=format&fit=crop",
    price: 27900,
    location: "Jodhpur, Rajasthan",
    duration: "1 day",
    participants: "1 person",
    date: "Year-round",
    category: "dining",
    nicheCategory: "Cooking"
  },
  {
    id: "exp71",
    title: "Rare Language Immersion",
    description: "Learn endangered Indian languages from native speakers in their traditional village settings.",
    imageUrl: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?q=80&w=2670&auto=format&fit=crop",
    price: 34900,
    location: "Multiple locations",
    duration: "7 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Literature"
  },
  {
    id: "exp72",
    title: "Observatory Night Experience",
    description: "Private access to a professional observatory with astronomers guiding your exploration of distant galaxies.",
    imageUrl: "https://images.unsplash.com/photo-1501862700950-18382cd41497?q=80&w=2719&auto=format&fit=crop",
    price: 17900,
    location: "Ooty, Tamil Nadu",
    duration: "1 night",
    participants: "2 people",
    date: "Clear sky nights",
    category: "learning",
    nicheCategory: "Astronomy"
  },
  {
    id: "exp73",
    title: "Ancient Fort Overnight Stay",
    description: "Exclusive overnight accommodation in a historic fort with royal heritage and authentic period furnishings.",
    imageUrl: "https://images.unsplash.com/photo-1524089161238-7a247ddf12e1?q=80&w=2670&auto=format&fit=crop",
    price: 59900,
    location: "Jaisalmer, Rajasthan",
    duration: "1 night",
    participants: "2 people",
    date: "October-March",
    category: "luxury",
    nicheCategory: "Heritage"
  },
  {
    id: "exp74",
    title: "Organic Tea Plantation Stay",
    description: "Experience life on an organic tea plantation with tea processing, tasting, and sustainable farming practices.",
    imageUrl: "https://images.unsplash.com/photo-1528407054915-e5dc4f3bfd5d?q=80&w=2574&auto=format&fit=crop",
    price: 21900,
    location: "Darjeeling, West Bengal",
    duration: "3 days",
    participants: "2 people",
    date: "March-October",
    category: "learning",
    nicheCategory: "Sustainable"
  },
  {
    id: "exp75",
    title: "Scuba Diving Certification Course",
    description: "Complete PADI certification in the crystal clear waters of the Andaman Islands with marine biologists.",
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=2670&auto=format&fit=crop",
    price: 49900,
    location: "Andaman Islands",
    duration: "5 days",
    participants: "1 person",
    date: "November-May",
    category: "adventure",
    nicheCategory: "Water Sports"
  },
  {
    id: "exp76",
    title: "Himalayan Ice Climbing",
    description: "Scale frozen waterfalls and ice walls with professional mountaineers and specialized ice climbing equipment.",
    imageUrl: "https://images.unsplash.com/photo-1516862523118-a3aceda15aa2?q=80&w=2574&auto=format&fit=crop",
    price: 42900,
    location: "Spiti Valley, Himachal Pradesh",
    duration: "5 days",
    participants: "1 person",
    date: "January-February",
    category: "adventure",
    nicheCategory: "Mountain"
  },
  {
    id: "exp77",
    title: "Snow Leopard Tracking Expedition",
    description: "Join wildlife conservationists in search of the elusive snow leopard in its natural high-altitude habitat.",
    imageUrl: "https://images.unsplash.com/photo-1585560063152-da83e47a8883?q=80&w=2670&auto=format&fit=crop",
    price: 89900,
    location: "Hemis National Park, Ladakh",
    duration: "8 days",
    participants: "1 person",
    date: "January-March",
    category: "adventure",
    nicheCategory: "Wildlife"
  },
  {
    id: "exp78",
    title: "Forest Bathing Retreat",
    description: "Experience the Japanese practice of shinrin-yoku (forest bathing) in pristine Himalayan forests.",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=2670&auto=format&fit=crop",
    price: 16900,
    location: "Binsar, Uttarakhand",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Meditation"
  },
  {
    id: "exp79",
    title: "Ultra Marathon Training Camp",
    description: "Train for ultra-distance running with elite coaches, physiotherapists, and nutrition experts.",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?q=80&w=2670&auto=format&fit=crop",
    price: 35900,
    location: "Ooty, Tamil Nadu",
    duration: "10 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Fitness"
  },
  {
    id: "exp80",
    title: "Sacred Pilgrimage Journey",
    description: "Travel the ancient Char Dham pilgrimage route with spiritual guides explaining traditions and rituals.",
    imageUrl: "https://images.unsplash.com/photo-1593225431962-f894fa83141d?q=80&w=2574&auto=format&fit=crop",
    price: 59900,
    location: "Uttarakhand",
    duration: "12 days",
    participants: "1 person",
    date: "May-June, September-October",
    category: "wellness",
    nicheCategory: "Spiritual"
  },
  {
    id: "exp81",
    title: "MiG-29 Fighter Jet Experience",
    description: "Fly in a supersonic fighter jet reaching heights of 22,000 meters with a professional military pilot.",
    imageUrl: "https://images.unsplash.com/photo-1531979866205-cf03c1a51f50?q=80&w=2670&auto=format&fit=crop",
    price: 249900,
    location: "Goa",
    duration: "1 day",
    participants: "1 person",
    date: "Limited availability",
    category: "adventure",
    nicheCategory: "Aviation"
  },
  {
    id: "exp82",
    title: "Floating Tent Camping Experience",
    description: "Sleep on a private floating platform tent in the middle of a tranquil lake surrounded by mountains.",
    imageUrl: "https://images.unsplash.com/photo-1515408320194-59643816c5b2?q=80&w=2426&auto=format&fit=crop",
    price: 32900,
    location: "Sattal, Uttarakhand",
    duration: "2 days",
    participants: "2 people",
    date: "March-November",
    category: "adventure",
    nicheCategory: "Camping"
  },
  {
    id: "exp83",
    title: "Living Root Bridge Trek",
    description: "Trek to see the unique living root bridges of Meghalaya, created by the Khasi tribe over generations.",
    imageUrl: "https://images.unsplash.com/photo-1515315411485-bb6722f124dd?q=80&w=2670&auto=format&fit=crop",
    price: 24900,
    location: "Meghalaya",
    duration: "4 days",
    participants: "1 person",
    date: "October-May",
    category: "adventure",
    nicheCategory: "Nature"
  },
  {
    id: "exp84",
    title: "Luxury Natural Hot Springs Retreat",
    description: "Relax in natural hot springs with private mineral pools and therapeutic treatments in a mountain setting.",
    imageUrl: "https://images.unsplash.com/photo-1654763152757-9737ed268e38?q=80&w=2574&auto=format&fit=crop",
    price: 38900,
    location: "Manikaran, Himachal Pradesh",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spa & Wellness"
  },
  {
    id: "exp85",
    title: "Professional Gaming Bootcamp",
    description: "Train with professional esports players and coaches to improve your skills in competitive gaming.",
    imageUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2671&auto=format&fit=crop",
    price: 29900,
    location: "Bengaluru, Karnataka",
    duration: "5 days",
    participants: "1 person",
    date: "Scheduled bootcamps",
    category: "learning",
    nicheCategory: "Gaming"
  },
  {
    id: "exp86",
    title: "Traditional Puppetry Workshop",
    description: "Learn the ancient art of Indian puppetry from master puppeteers and create your own puppet show.",
    imageUrl: "https://images.unsplash.com/photo-1508261301992-f7fb3e6e4a56?q=80&w=2574&auto=format&fit=crop",
    price: 14900,
    location: "Jaipur, Rajasthan",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Performance Arts"
  },
  {
    id: "exp87",
    title: "Diwali Festival in a Royal Palace",
    description: "Celebrate Diwali with a royal family in their palace with traditional ceremonies and lavish festivities.",
    imageUrl: "https://images.unsplash.com/photo-1605214178469-811195b618eb?q=80&w=2574&auto=format&fit=crop",
    price: 49900,
    location: "Rajasthan",
    duration: "3 days",
    participants: "2 people",
    date: "During Diwali",
    category: "luxury",
    nicheCategory: "Seasonal"
  },
  {
    id: "exp88",
    title: "Space Camp for Adults",
    description: "Train like an astronaut with zero-gravity simulation, spacecraft operation, and astrophysics workshops.",
    imageUrl: "https://images.unsplash.com/photo-1502134249126-9f3755a50d78?q=80&w=2670&auto=format&fit=crop",
    price: 59900,
    location: "Bengaluru, Karnataka",
    duration: "5 days",
    participants: "1 person",
    date: "Scheduled programs",
    category: "learning",
    nicheCategory: "Science"
  },
  {
    id: "exp89",
    title: "Luxury Cat Cafe Retreat",
    description: "Stay in luxury accommodations where rescue cats roam freely, with cat yoga and feline behavior workshops.",
    imageUrl: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?q=80&w=2670&auto=format&fit=crop",
    price: 18900,
    location: "Mumbai, Maharashtra",
    duration: "2 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Pet-friendly"
  },
  {
    id: "exp90",
    title: "Bungee Jumping Master Course",
    description: "Progress from basic jumps to advanced techniques with professional bungee instructors at India's highest jump site.",
    imageUrl: "https://images.unsplash.com/photo-1547176326-d9ba66be61ea?q=80&w=2680&auto=format&fit=crop",
    price: 22900,
    location: "Rishikesh, Uttarakhand",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round except monsoon",
    category: "adventure",
    nicheCategory: "Extreme Sports"
  },
  {
    id: "exp91",
    title: "Astrophotography Masterclass",
    description: "Learn to capture stunning images of the night sky with specialized equipment and post-processing techniques.",
    imageUrl: "https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?q=80&w=2671&auto=format&fit=crop",
    price: 27900,
    location: "Nubra Valley, Ladakh",
    duration: "4 days",
    participants: "1 person",
    date: "May-September",
    category: "learning",
    nicheCategory: "Photography"
  },
  {
    id: "exp92",
    title: "Himalayan Textile Weaving",
    description: "Learn traditional Himalayan weaving techniques and create your own textile piece using ancient looms.",
    imageUrl: "https://images.unsplash.com/photo-1599471914433-1faf64a5c5e5?q=80&w=2574&auto=format&fit=crop",
    price: 19900,
    location: "Kullu, Himachal Pradesh",
    duration: "5 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Art & Crafts"
  },
  {
    id: "exp93",
    title: "Monsoon Music Festival VIP Experience",
    description: "Premium access to an exclusive music festival held during the monsoon season in a historic fort.",
    imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?q=80&w=2670&auto=format&fit=crop",
    price: 35900,
    location: "Lonavala, Maharashtra",
    duration: "3 days",
    participants: "2 people",
    date: "July-August",
    category: "luxury",
    nicheCategory: "Music"
  },
  {
    id: "exp94",
    title: "Chef's Table Molecular Gastronomy",
    description: "Learn the science of molecular gastronomy with award-winning chefs and create innovative dishes.",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2670&auto=format&fit=crop",
    price: 32900,
    location: "Bengaluru, Karnataka",
    duration: "1 day",
    participants: "1 person",
    date: "Year-round",
    category: "dining",
    nicheCategory: "Cooking"
  },
  {
    id: "exp95",
    title: "Ancient Manuscript Restoration",
    description: "Learn the delicate art of ancient manuscript restoration and conservation from museum experts.",
    imageUrl: "https://images.unsplash.com/photo-1457543992015-7e8278871a52?q=80&w=2672&auto=format&fit=crop",
    price: 21900,
    location: "Multiple locations",
    duration: "3 days",
    participants: "1 person",
    date: "Limited availability",
    category: "learning",
    nicheCategory: "Literature"
  },
  {
    id: "exp96",
    title: "Solar Eclipse Viewing Expedition",
    description: "Travel to the ideal location to witness a solar eclipse with specialized viewing equipment and experts.",
    imageUrl: "https://images.unsplash.com/photo-1532798369041-b23a5f37a446?q=80&w=2582&auto=format&fit=crop",
    price: 42900,
    location: "Location varies by eclipse",
    duration: "3 days",
    participants: "1 person",
    date: "During solar eclipses",
    category: "adventure",
    nicheCategory: "Astronomy"
  },
  {
    id: "exp97",
    title: "Mughal Architecture Tour",
    description: "Explore the finest examples of Mughal architecture with historians and conservation specialists.",
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=2671&auto=format&fit=crop",
    price: 29900,
    location: "Delhi, Agra, Fatehpur Sikri",
    duration: "4 days",
    participants: "2 people",
    date: "October-March",
    category: "learning",
    nicheCategory: "Heritage"
  },
  {
    id: "exp98",
    title: "Himalayan Permaculture Workshop",
    description: "Learn sustainable living and permaculture design principles adapted for mountain environments.",
    imageUrl: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?q=80&w=2670&auto=format&fit=crop",
    price: 24900,
    location: "Dharamshala, Himachal Pradesh",
    duration: "7 days",
    participants: "1 person",
    date: "April-October",
    category: "learning",
    nicheCategory: "Sustainable"
  },
  {
    id: "exp99",
    title: "Luxury Yacht Sailing Journey",
    description: "Sail on a luxury yacht along the stunning Konkan coast with a professional crew and gourmet dining.",
    imageUrl: "https://images.unsplash.com/photo-1499571466513-0f39da6eb10b?q=80&w=2672&auto=format&fit=crop",
    price: 129900,
    location: "Konkan Coast, Maharashtra",
    duration: "4 days",
    participants: "4 people",
    date: "October-May",
    category: "luxury",
    nicheCategory: "Water Sports"
  },
  {
    id: "exp100",
    title: "Everest Base Camp Helicopter Expedition",
    description: "Fly to Mount Everest Base Camp by helicopter with breakfast overlooking the world's highest peak.",
    imageUrl: "https://images.unsplash.com/photo-1503425000275-fc53cb17ad2a?q=80&w=2670&auto=format&fit=crop",
    price: 149900,
    location: "Nepal",
    duration: "1 day",
    participants: "1 person",
    date: "March-May, September-November",
    category: "adventure",
    nicheCategory: "Mountain"
  },
  {
    id: "exp101",
    title: "Elephant Conservation Experience",
    description: "Work alongside elephant conservationists caring for rescued elephants in a natural sanctuary.",
    imageUrl: "https://images.unsplash.com/photo-1509993623183-b8e3755246b1?q=80&w=2670&auto=format&fit=crop",
    price: 32900,
    location: "Mathura, Uttar Pradesh",
    duration: "3 days",
    participants: "1 person",
    date: "Year-round",
    category: "adventure",
    nicheCategory: "Wildlife"
  },
  {
    id: "exp102",
    title: "Zen Meditation in Himalayan Cave",
    description: "Practice Zen meditation techniques in a remote Himalayan cave with a meditation master.",
    imageUrl: "https://images.unsplash.com/photo-1487088678257-3a541e6e3922?q=80&w=2574&auto=format&fit=crop",
    price: 22900,
    location: "Spiti Valley, Himachal Pradesh",
    duration: "5 days",
    participants: "1 person",
    date: "May-September",
    category: "wellness",
    nicheCategory: "Meditation"
  },
  {
    id: "exp103",
    title: "Olympic Athlete Training Experience",
    description: "Train with Olympic athletes and coaches using professional facilities and personalized programs.",
    imageUrl: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2669&auto=format&fit=crop",
    price: 45900,
    location: "Multiple locations",
    duration: "7 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Fitness"
  },
  {
    id: "exp104",
    title: "Hindu-Buddhist Philosophy Retreat",
    description: "Immerse in Hindu and Buddhist philosophical teachings with renowned scholars in a tranquil setting.",
    imageUrl: "https://images.unsplash.com/photo-1599582302484-e01f46c9f4fd?q=80&w=2680&auto=format&fit=crop",
    price: 28900,
    location: "Rishikesh, Uttarakhand",
    duration: "7 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spiritual"
  },
  {
    id: "exp105",
    title: "Aerobatic Flight Experience",
    description: "Experience thrilling aerobatic maneuvers with a professional stunt pilot in a high-performance aircraft.",
    imageUrl: "https://images.unsplash.com/photo-1498581444814-7e44d2fbe0e2?q=80&w=2670&auto=format&fit=crop",
    price: 42900,
    location: "Bengaluru, Karnataka",
    duration: "Half-day",
    participants: "1 person",
    date: "Year-round",
    category: "adventure",
    nicheCategory: "Aviation"
  },
  {
    id: "exp106",
    title: "Himalayan Nomadic Camp Experience",
    description: "Travel with nomadic shepherds in the Himalayas, staying in traditional camps and learning their way of life.",
    imageUrl: "https://images.unsplash.com/photo-1632402515404-b5ebb1d53f3c?q=80&w=2670&auto=format&fit=crop",
    price: 39900,
    location: "Ladakh",
    duration: "7 days",
    participants: "1 person",
    date: "June-September",
    category: "adventure",
    nicheCategory: "Camping"
  },
  {
    id: "exp107",
    title: "Silent Valley Biodiversity Expedition",
    description: "Explore one of the world's most biodiverse rainforests with conservation scientists and wildlife experts.",
    imageUrl: "https://images.unsplash.com/photo-1490776501473-4b23364a8dc4?q=80&w=2670&auto=format&fit=crop",
    price: 27900,
    location: "Silent Valley, Kerala",
    duration: "4 days",
    participants: "1 person",
    date: "October-March",
    category: "adventure",
    nicheCategory: "Nature"
  },
  {
    id: "exp108",
    title: "Ancient Ayurvedic Rejuvenation",
    description: "Experience the most authentic and comprehensive Ayurvedic treatments based on ancient Sanskrit texts.",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=2670&auto=format&fit=crop",
    price: 65900,
    location: "Thrissur, Kerala",
    duration: "14 days",
    participants: "1 person",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Spa & Wellness"
  },
  {
    id: "exp109",
    title: "Game Development Hackathon",
    description: "Participate in an intensive game development competition with industry professionals and cutting-edge tools.",
    imageUrl: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?q=80&w=2670&auto=format&fit=crop",
    price: 18900,
    location: "Pune, Maharashtra",
    duration: "3 days",
    participants: "1 person",
    date: "Scheduled events",
    category: "learning",
    nicheCategory: "Gaming"
  },
  {
    id: "exp110",
    title: "Opera Training Workshop",
    description: "Develop your operatic skills with renowned vocal coaches and performers in a professional setting.",
    imageUrl: "https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=2574&auto=format&fit=crop",
    price: 42900,
    location: "Mumbai, Maharashtra",
    duration: "7 days",
    participants: "1 person",
    date: "Twice yearly",
    category: "learning",
    nicheCategory: "Performance Arts"
  },
  {
    id: "exp111",
    title: "Monsoon Photography Expedition",
    description: "Capture the dramatic landscapes and vibrant life that emerges during India's monsoon season.",
    imageUrl: "https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?q=80&w=2674&auto=format&fit=crop",
    price: 28900,
    location: "Western Ghats",
    duration: "5 days",
    participants: "1 person",
    date: "June-September",
    category: "learning",
    nicheCategory: "Seasonal"
  },
  {
    id: "exp112",
    title: "Nuclear Research Facility Tour",
    description: "Exclusive behind-the-scenes tour of nuclear research facilities with scientists explaining their work.",
    imageUrl: "https://images.unsplash.com/photo-1636458938709-0060e4e17b18?q=80&w=2574&auto=format&fit=crop",
    price: 24900,
    location: "Mumbai, Maharashtra",
    duration: "1 day",
    participants: "1 person",
    date: "Limited availability",
    category: "learning",
    nicheCategory: "Science"
  },
  {
    id: "exp113",
    title: "Dog Yoga Retreat",
    description: "Practice 'doga' (dog yoga) with your canine companion in a peaceful retreat setting with specialized instructors.",
    imageUrl: "https://images.unsplash.com/photo-1591946614720-90a587da4a36?q=80&w=2574&auto=format&fit=crop",
    price: 15900,
    location: "Coorg, Karnataka",
    duration: "3 days",
    participants: "1 person + 1 dog",
    date: "Year-round",
    category: "wellness",
    nicheCategory: "Pet-friendly"
  },
  {
    id: "exp114",
    title: "Himalayan Ice Marathon",
    description: "Run a marathon on the frozen Zanskar River, one of the world's most extreme race environments.",
    imageUrl: "https://images.unsplash.com/photo-1486218119243-13883505764c?q=80&w=2672&auto=format&fit=crop",
    price: 49900,
    location: "Ladakh",
    duration: "5 days",
    participants: "1 person",
    date: "January-February",
    category: "adventure",
    nicheCategory: "Extreme Sports"
  },
  {
    id: "exp115",
    title: "Tribal Photography Cultural Immersion",
    description: "Document the lives and traditions of remote tribal communities with ethical photography practices.",
    imageUrl: "https://images.unsplash.com/photo-1573773688198-be6e5a4d3c49?q=80&w=2670&auto=format&fit=crop",
    price: 32900,
    location: "Odisha",
    duration: "7 days",
    participants: "1 person",
    date: "October-March",
    category: "learning",
    nicheCategory: "Photography"
  },
  {
    id: "exp116",
    title: "Traditional Jewelry Making",
    description: "Learn ancient metal-working techniques to create traditional Indian jewelry with master craftspeople.",
    imageUrl: "https://images.unsplash.com/photo-1517999349371-c43e7f066099?q=80&w=2574&auto=format&fit=crop",
    price: 21900,
    location: "Jaipur, Rajasthan",
    duration: "4 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Art & Crafts"
  },
  {
    id: "exp117",
    title: "Classical Music Recording Session",
    description: "Record your own performance with professional classical musicians in a state-of-the-art studio.",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=2670&auto=format&fit=crop",
    price: 48900,
    location: "Chennai, Tamil Nadu",
    duration: "2 days",
    participants: "1 person",
    date: "Year-round",
    category: "learning",
    nicheCategory: "Music"
  },
  {
    id: "exp118",
    title: "Himalayan Wild Food Foraging",
    description: "Learn to identify, forage, and prepare wild Himalayan foods with expert foragers and chefs.",
    imageUrl: "https://images.unsplash.com/photo-1470549638415-0a0755be0619?q=80&w=2728&auto=format&fit=crop",
    price: 24900,
    location: "Himachal Pradesh",
    duration: "3 days",
    participants: "1 person",
    date: "April-October",
    category: "dining",
    nicheCategory: "Cooking"
  }
];

export const categories: Category[] = [
  {
    id: "cat1",
    name: "Adventure",
    description: "Thrilling experiences for adrenaline seekers",
    imageUrl: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?q=80&w=2688&auto=format&fit=crop",
    icon: Users
  },
  {
    id: "cat2",
    name: "Dining",
    description: "Exceptional culinary experiences",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=2574&auto=format&fit=crop",
    icon: Gift
  },
  {
    id: "cat3",
    name: "Wellness",
    description: "Relaxation and rejuvenation",
    imageUrl: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=2678&auto=format&fit=crop",
    icon: Calendar
  },
  {
    id: "cat4",
    name: "Luxury",
    description: "Premium exclusive experiences",
    imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2670&auto=format&fit=crop",
    icon: MapPin
  },
  {
    id: "cat5",
    name: "Learning",
    description: "Educational and skill-building activities",
    imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=2622&auto=format&fit=crop",
    icon: Clock
  }
];
